# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
configfile: "config/config.yaml"

pepfile: config["pepfile"]

include: "rules/common.smk"
include: "rules/analysis.smk"


rule all:
    input:
        expand("/results/{date}/analysis/card/{sample}/{sample}.txt", date=get_run_date(), sample=get_samples()),